### ISSUE TITLE
Design Suggestions

### ISSUE THREAD

**Issue by jdugan6240** [hadronized/kak-tree-sitter#138] opened 2023-09-24 23:56 UTC
Hey, this is a really nice project. I have a few suggestions that I believe would make it more user-friendly.
- _**Map highlighting queries to Kakoune faces instead of options.**_ Essentially, in the kak-tree-sitter config, instead of `highlight.groups` just being a list of queries you're enabling, you'd have a table matching queries to Kakoune faces, for example matching `comment.line`, etc to the `comment` face. This would keep you from having to define an option for each query you want to support, and you'd get [#78](https://github.com/phaazon/kak-tree-sitter/issues/78) for free since you're using the faces colorschemes already use for syntax highlighting. [tree-sitter.kak](https://github.com/enricozb/tree-sitter.kak) does this, I believe.
- _**Grab query files from the tree sitter grammar repos, or only clone Helix once.**_ As is, ktsctl needs to re-clone Helix (a rather large repository) for each grammar that the user installs. This is a waste of disk space, and it would be better if either only one Helix copy was needed (basically ktsctl would only clone it if it hasn't already), or we could just use the query files that come with the grammars.
- _**Compile grammars without forcing the user to define the compile args.**_ ktsctl should support compiling grammars without the user needing to tell it how. [py-tree-sitter](https://github.com/tree-sitter/py-tree-sitter/blob/a0ceeb1e50b1ecf5b26924b567da99eb58a4b401/tree_sitter/__init__.py#L40C14-L40C14) (the Python bindings for tree-sitter) defines a method for building the library file by just passing it the output path and the repo path - it handles finding the source files and linking it correctly. I'd imagine something similar could be done in ktsctl (rust's tree-sitter binding doesn't have such a function, unfortunately)
- _**Don't remove the default highlighting by default.**_ Sadly, some grammars, such as the [Nim grammar](https://github.com/aMOPel/tree-sitter-nim), aren't comprehensive, and this combined with the fact that the user may not have all the necessary queries defined in `config.toml` means that some holes may be left in kak-tree-sitter's highlighting. It would be nice to give the user the option to keep the default syntax highlighting as a fallback in cases like these.

You don't need to implement all, or really any, of these if they don't match your vision of the project. I have my own (very WIP) implementation [here](https://github.com/jdugan6240/kak-tree-sitter), but I'd like to be able to use yours since Rust is obviously more performant than Python.

**Comment by phaazon** [comment] 2023-09-29 09:58
> Map highlighting queries to Kakoune faces instead of options. Essentially, in the kak-tree-sitter config, instead of highlight.groups just being a list of queries you're enabling, you'd have a table matching queries to Kakoune faces, for example matching comment.line, etc to the comment face. This would keep you from having to define an option for each query you want to support, and you'd get https://github.com/phaazon/kak-tree-sitter/issues/78 for free since you're using the faces colorschemes already use for syntax highlighting. [tree-sitter.kak](https://github.com/enricozb/tree-sitter.kak) does this, I believe.

Yes, I initially wanted to do that, but I’m not sure which faces to target. The problem is that the default colorscheme is not standardized and every colorscheme does a bit whatever it wants. There are the default highlighters with a bunch of common faces, but it’s not sufficient. Something that could be done would be to still use those, and give the opportunity to provide more later on. As you said, highlight groups could be faces targetting default faces, but colorschemes could still override them.

The problem with that is that I don’t think colorschemes are going to support my plugin. It doesn’t scale very well. So I’d rather have just more default faces everyone agrees on.

> Grab query files from the tree sitter grammar repos, or only clone Helix once. As is, ktsctl needs to re-clone Helix (a rather large repository) for each grammar that the user installs. This is a waste of disk space, and it would be better if either only one Helix copy was needed (basically ktsctl would only clone it if it hasn't already), or we could just use the query files that come with the grammars.

This is especially true for a feature I want to add to `ktsctl`: being able to specify many languages at once. Indeed, most queries come from Helix, and I reclone the whole repository everytime for each new language to support. I wouldn’t say it’s really a waste of disk space because I clone into a tmpfs, which should be removed as soon as the user reboots, but if the user reboots rarely, yes, that’s a problem. I might also add a `ktsctl --clear` flag for that.

I also don’t want to give in to fully use Helix queries. Something that could be done would be to clone in the first place, and then simply use `git checkout`. Shouldn’t be very hard to do, but I want to be sure that we don’t « force » to use Helix queries.

> Compile grammars without forcing the user to define the compile args. ktsctl should support compiling grammars without the user needing to tell it how. [py-tree-sitter](https://github.com/tree-sitter/py-tree-sitter/blob/a0ceeb1e50b1ecf5b26924b567da99eb58a4b401/tree_sitter/__init__.py#L40C14-L40C14) (the Python bindings for tree-sitter) defines a method for building the library file by just passing it the output path and the repo path - it handles finding the source files and linking it correctly. I'd imagine something similar could be done in ktsctl (rust's tree-sitter binding doesn't have such a function, unfortunately)

If you find a way how, I’m all ears. We could look at whether the source code is C or C++ to link correctly, but I’m not entirely sure about the rest (do grammars sometimes link to external libraries?), so for now I have just this very plain static and simple list of arguments. I agree it’s not ideal, but a _end-user_ is not supposed to modify the `config.toml` file and instead just use `ktsctl --has` and `ktsctl -fci`.

> Don't remove the default highlighting by default. Sadly, some grammars, such as the [Nim grammar](https://github.com/aMOPel/tree-sitter-nim), aren't comprehensive, and this combined with the fact that the user may not have all the necessary queries defined in config.toml means that some holes may be left in kak-tree-sitter's highlighting. It would be nice to give the user the option to keep the default syntax highlighting as a fallback in cases like these.

That’s a good point.

**Comment by jdugan6240** [comment] 2023-09-30 20:26
Most of what you said makes sense, but I guess I just don't understand the rationale for not using the default faces. Colorschemes don't need to support your plugin specifically if you use those. For instance, here's what I have in my kakrc to support any colorscheme:

```kak
    evaluate-commands %sh{ kak-tree-sitter -dks --session $kak_session }
    # Fix faces to work with any colorscheme
    set-face global ts_attribute                    "attribute"
    set-face global ts_comment                      "comment"
    set-face global ts_comment_block                "ts_comment"
    set-face global ts_comment_line                 "ts_comment"
    set-face global ts_conceal                      "+i@meta"
    set-face global ts_constant                     "value"
    set-face global ts_constant_builtin_boolean     "builtin"
    set-face global ts_constant_character           "string"
    set-face global ts_constant_character_escape    "value"
    set-face global ts_constant_macro               "meta"
    set-face global ts_constant_numeric             "value"
    set-face global ts_constant_numeric_float       "value"
    set-face global ts_constant_numeric_integer     "value"
    set-face global ts_constructor                  "function"
    set-face global ts_diff_plus                    "green"
    set-face global ts_diff_minus                   "red"
    set-face global ts_diff_delta                   "blue"
    set-face global ts_diff_delta_moved             "blue"
    set-face global ts_error                        "Error"
    set-face global ts_function                     "function"
    set-face global ts_function_builtin             "builtin"
    set-face global ts_function_macro               "meta"
    set-face global ts_function_method              "function"
    set-face global ts_function_special             "function"
    set-face global ts_hint                         "Information"
    set-face global ts_info                         "Information"
    set-face global ts_keyword                      "keyword"
    set-face global ts_keyword_control              "ts_keyword"
    set-face global ts_keyword_conditional          "ts_keyword"
    set-face global ts_keyword_control_conditional  "ts_keyword"
    set-face global ts_keyword_control_directive    "ts_keyword"
    set-face global ts_keyword_control_import       "ts_keyword"
    set-face global ts_keyword_control_repeat       "ts_keyword"
    set-face global ts_keyword_control_return       "ts_keyword"
    set-face global ts_keyword_control_except       "ts_keyword"
    set-face global ts_keyword_control_exception    "ts_keyword"
    set-face global ts_keyword_directive            "ts_keyword"
    set-face global ts_keyword_function             "ts_keyword"
    set-face global ts_keyword_operator             "ts_keyword"
    set-face global ts_keyword_special              "ts_keyword"
    set-face global ts_keyword_storage              "ts_keyword"
    set-face global ts_keyword_storage_modifier     "ts_keyword"
    set-face global ts_keyword_storage_modifier_mut "ts_keyword"
    set-face global ts_keyword_storage_modifier_ref "ts_keyword"
    set-face global ts_keyword_storage_type         "ts_keyword"
    set-face global ts_label                        "+i@Default"
    set-face global ts_markup_bold                  "+b@Default"
    set-face global ts_markup_heading               "header"
    set-face global ts_markup_heading_1             "header"
    set-face global ts_markup_heading_2             "header"
    set-face global ts_markup_heading_3             "header"
    set-face global ts_markup_heading_4             "header"
    set-face global ts_markup_heading_5             "header"
    set-face global ts_markup_heading_6             "header"
    set-face global ts_markup_heading_marker        "+b@header"
    set-face global ts_markup_italic                "+i@header"
    set-face global ts_markup_list_checked          "list"
    set-face global ts_markup_list_numbered         "list"
    set-face global ts_markup_list_unchecked        "list"
    set-face global ts_markup_list_unnumbered       "bullet"
    set-face global ts_markup_link_label            "link"
    set-face global ts_markup_link_url              "+u@link"
    set-face global ts_markup_link_uri              "+u@link"
    set-face global ts_markup_link_text             "link"
    set-face global ts_markup_quote                 "string"
    set-face global ts_markup_raw                   "string"
    set-face global ts_markup_raw_block             "string"
    set-face global ts_markup_raw_inline            "string"
    set-face global ts_markup_strikethrough         "+s@string"
    set-face global ts_namespace                    "module"
    set-face global ts_operator                     "operator"
    set-face global ts_property                     "attribute"
    set-face global ts_punctuation                  "operator"
    set-face global ts_punctuation_bracket          "ts_punctuation"
    set-face global ts_punctuation_delimiter        "ts_punctuation"
    set-face global ts_punctuation_special          "ts_punctuation"
    set-face global ts_special                      "meta"
    set-face global ts_spell                        "meta"
    set-face global ts_string                       "string"
    set-face global ts_string_regex                 "string"
    set-face global ts_string_regexp                "string"
    set-face global ts_string_escape                "value"
    set-face global ts_string_special               "string"
    set-face global ts_string_special_path          "string"
    set-face global ts_string_special_symbol        "string"
    set-face global ts_string_symbol                "string"
    set-face global ts_tag                          "meta"
    set-face global ts_tag_error                    "Error"
    set-face global ts_text                         "Default"
    set-face global ts_text_title                   "header"
    set-face global ts_type                         "type"
    set-face global ts_type_builtin                 "builtin"
    set-face global ts_type_enum_variant            "type"
    set-face global ts_variable                     "variable"
    set-face global ts_variable_builtin             "builtin"
    set-face global ts_variable_other_member        "variable"
    set-face global ts_variable_parameter           "variable"
    set-face global ts_warning                      "DiagnosticWarning"
```

As you can see, all of the faces used come from the default colorscheme (minus some italics, bold, underline, etc), which only defines the bare minimum of faces colorschemes must support. As a result, if you change colorschemes here, the tree sitter highlighting changes accordingly, just like the standard syntax highlighters. 

I genuinely don't understand why custom faces are needed here - with the current system, you need to specify them in both the kak-tree-sitter config.toml and your kakrc, which seems redundant to me. If you just had a table in config.toml specifying which face matches which query, you'd effortlessly support every colorscheme without them needing to explicitly support your plugin at all, and it's easy for the user to change if need be. Best of all, if a new grammar uses queries that we don't handle yet, supporting them is as easy as updating the config.toml file.

If you don't want to do things this way, the above kakrc code does work for my use case, but I urge you to reconsider your position on this.

**Comment by phaazon** [comment] 2023-10-17 15:54
That was my initial idea, but:

1. How do we define what face is _default_ and what is not?
2. From what I saw, the “default” (assuming the most commonly distributed `.kak` color files) faces are not enough to provide a par highlighting compared to e.g. Helix.

So yes, I agree that it should be the way to go. I would much more appreciate a real list of curated faces to use. If you think I’m mistaken because that list would exist, I’d be happy to admit I’m wrong and immediately implement the feature with this list.

**Comment by jdugan6240** [comment] 2023-10-17 18:00
> From what I saw, the “default” (assuming the most commonly distributed .kak color files) faces are not enough to provide a par highlighting compared to e.g. Helix.

Ah, I see. If you think there just aren't enough faces defined in colors/default.kak to achieve the result you want, then that's fair enough. For something like this to work across colorschemes, it would need to stick to the faces in that file, with the exception of some transformations like bold and italics.

I find that the faces defined in default.kak are enough for me for the most part, but I suppose it's not a bad idea to support more varied highlighting by default (Kakoune's default code faces for instance only contain one keyword face). 

Would it be enough if I just added the kakrc snippet I posted to the wiki, so users can just use that if they wish? I'd be happy to add explicit kak-tree-sitter support to my [everforest port](https://github.com/jdugan6240/everforest.kak), as well.

**Comment by phaazon** [comment] 2023-10-19 16:10
I think we need a hybrid approach. I would eventually agree to just use the default faces, but I do want our users to feel that everything is simple and nice right away.

Something I thought initially was to export a subset of `ts_*` faces. That would allow colorschemes to easily implement a « fixed » set of faces, with most of them based on the default faces. Then, `ts_*` would be defined mainly by either other `ts_*` or the default ones. If a new language has a super specific `@keyword.super.specific` highlight group, we could simply declare it as:

```
set-face global ts_keyword_super_specific ts_keyword
```

So this is basically what you suggest IIUC, but a couple of annoying things to me:

- By default, we assume colorschemes do not implement the important `ts_*` faces.
- The default faces are pretty poor compared to a full support of the colorscheme.

I think we should start listing the « important » faces, mainly with some variations, for instance:

- `ts_constant`, `ts_constant_character`, `ts_constant_numeric`, etc. should be in the exported list, even though they would have some default values.
- `ts_punctuation`, `ts_punctuation_delimiter`, `ts_punctuation_bracket`, etc. same thing.

Generating that list and pushing it to the wiki should be fairly simple.

**Comment by igor-ramazanov** [comment] 2023-12-30 02:50
[This](https://github.com/kak-lsp/kak-lsp/pull/706#discussion_r1438150188) won't work if `kak-tree-sitter` does not use common Kakoune code faces.

**Comment by jdugan6240** [comment] 2023-12-30 20:02
> [This](https://github.com/kak-lsp/kak-lsp/pull/706#discussion_r1438150188) won't work if `kak-tree-sitter` does not use common Kakoune code faces.

While true, it would be possible to set the `ts_` options to refer to the default code faces defined by Kakoune. I believe that's more or less what @phaazon wants to do, and I posted a snippet that does exactly that earlier in this thread.

**Comment by igor-ramazanov** [comment] 2023-12-30 20:03
@jdugan6240 Ah, yeah, exactly. I forgot about this way.

**Comment by igor-ramazanov** [comment] 2023-12-31 08:38
Something more to the table: it should be possible to write code which converts Helix *.toml theme to kak-tree-sitter's *.kak, since they both use the same Tree Sitter naming conventions.

Not sure how to make it interplay well with Kakoune built-in faces, perhaps, converting from Helix `ui.*` values?

**Comment by jdugan6240** [comment] 2023-12-31 17:24
The problem with making something like that interplay with Kakoune's builtin faces is that the builtin faces aren't static - their exact values depend on the colorscheme, and some faces may well share the same color value. So, you'd have a hard time determining if a certain hex value from a Helix colorscheme corresponds to one of Kakoune's builtin faces.

**Comment by jdugan6240** [comment] 2023-12-31 17:29
> The problem with making something like that interplay with Kakoune's builtin faces is that the builtin faces aren't static - their exact values depend on the colorscheme, and some faces may well share the same color value. So, you'd have a hard time determining if a certain hex value from a Helix colorscheme corresponds to one of Kakoune's builtin faces. A simple Helix->Kakoune converter should be easy enough, though, if we don't use the builtin faces.

**Comment by igor-ramazanov** [comment] 2023-12-31 17:43
@jdugan6240

> The problem with making something like that interplay with Kakoune's builtin faces is that the builtin faces aren't static - their exact values depend on the colorscheme,

I don't think there is a problem, or maybe I missed something.

Here's my thought:
1. There is a connection between `helix` and `kak-tree-sitter` `tree-sitter` queries. `helix` -> `kak-tree-sitter` translation.
    -  We can pick a subset of `kak-tree-sitter` to be used as Kakoune builtin code faces. `kak-tree-sitter` -> `Kakoune builtin faces for code`.
2. There is a connection between `helix` UI colors and Kakoune builtin interface faces. `helix` -> `Kakoune faces for everything else except the code`.

Doesn't look like anything is missed?

I'll try to create a PoC to generate one colorscheme for Kakoune from a Helix which would support both Kakoune builtin faces and `kak-tree-sitter` ones.

**Comment by jdugan6240** [comment] 2023-12-31 17:44
The problem is what hex values correspond to which builtin faces? Without knowing the Kakoune colorscheme being used, there's no way to know.

**Comment by igor-ramazanov** [comment] 2023-12-31 17:53
@jdugan6240 I still don't understand the problem :)

A small example:

1. [helix](https://github.com/helix-editor/helix/blob/85fce2f5b6c9f35ab9d3361f3933288a28db83d4/runtime/themes/nord.toml#L12) -> [kakoune](https://github.com/phaazon/kak-tree-sitter/blob/master/kak-tree-sitter/rc/static.kak#L157)
    - [kakoune](https://github.com/phaazon/kak-tree-sitter/blob/d7dc3dc2f9e25596ed1c45430c469aa22404d05b/kak-tree-sitter/rc/static.kak#L157) -> [Kakoune code](https://github.com/mawww/kakoune/blob/83fb65aef5729167b47c6ec22a57e5bd6ac5a9ae/colors/default.kak#L4)
2. [helix UI](https://github.com/helix-editor/helix/blob/85fce2f5b6c9f35ab9d3361f3933288a28db83d4/runtime/themes/nord.toml#L100C10-L100C10) -> [Kakoune UI](https://github.com/mawww/kakoune/blob/83fb65aef5729167b47c6ec22a57e5bd6ac5a9ae/colors/default.kak#L40)

We just need to create such mappings, then it'd possible to convert any Helix theme to Kakoune which would work both with or without `kak-tree-sitter`.

**Comment by jdugan6240** [comment] 2023-12-31 18:53
> @jdugan6240 I still don't understand the problem :)
> 
> A small example:
> 
> 1. [helix](https://github.com/helix-editor/helix/blob/85fce2f5b6c9f35ab9d3361f3933288a28db83d4/runtime/themes/nord.toml#L12) -> [kakoune](https://github.com/phaazon/kak-tree-sitter/blob/master/kak-tree-sitter/rc/static.kak#L157)
>     - [kakoune](https://github.com/phaazon/kak-tree-sitter/blob/d7dc3dc2f9e25596ed1c45430c469aa22404d05b/kak-tree-sitter/rc/static.kak#L154) -> [Kakoune code](https://github.com/mawww/kakoune/blob/83fb65aef5729167b47c6ec22a57e5bd6ac5a9ae/colors/default.kak#L4)
> 2. [helix UI](https://github.com/helix-editor/helix/blob/85fce2f5b6c9f35ab9d3361f3933288a28db83d4/runtime/themes/nord.toml#L100) -> [Kakoune UI](https://github.com/mawww/kakoune/blob/83fb65aef5729167b47c6ec22a57e5bd6ac5a9ae/colors/default.kak#L40)
> 
> We just need to create such mappings, then it'd possible to convert any Helix theme to Kakoune which would work both with or without `kak-tree-sitter`.

Ok, let me explain the issue with an example. In Helix's solarized dark colorscheme, for instance, the "string" color is #2aa198. Normally, you'd just map this to the "string" face, because obviously, but [some colorschemes](https://github.com/sainnhe/everforest/issues/128) have deliberate differences between tree sitter highlighting and "regular" syntax highlighting, so this isn't a safe general assumption. This means that a tool like this has to work with the raw hex values, which would have the issues I mentioned before where different Kakoune colorschemes define faces differently, making matching hex values to faces difficult.

Does this clear things up?

**Comment by igor-ramazanov** [comment] 2023-12-31 20:02
@jdugan6240 Ahaaa, yeah, I see now.

It's like here, for example: 
![image](https://github.com/phaazon/kak-tree-sitter/assets/12570166/875f1e53-c96f-41c4-a0cc-3bd576b9ba71).

That's a different flavours of Solarized with different colors granularity: sixteen (a full, original one) or different ones with five colours only for less granular environments.

Damn, that makes it a lot harder indeed.

**Comment by phaazon** [comment] 2024-01-15 10:19
All of that to say: doggammit!

**Comment by hadronized** [comment] 2024-03-04 19:47
I’m going to close this as it contains outdated feature requests or not scoped enough one (and we over duplicates here and there). Feel free to reopen a more narrowed version if you think I missed something.

**Closed by hadronized** 2024-03-04 19:47 UTC
Labels: TBD
